"""empty message

Revision ID: 45552d558ce6
Revises: e869b6f1d9c1
Create Date: 2018-10-28 02:52:56.276252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45552d558ce6'
down_revision = 'e869b6f1d9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenumaster', sa.Column('submenu_name', sa.String(length=256), nullable=False))
    op.drop_column('submenumaster', 'subcategory_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenumaster', sa.Column('subcategory_name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('submenumaster', 'submenu_name')
    # ### end Alembic commands ###
