"""empty message

Revision ID: 46a14685f059
Revises: d7762c6ed2e7
Create Date: 2018-10-25 21:09:48.898280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46a14685f059'
down_revision = 'd7762c6ed2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menumaster', sa.Column('menu_name', sa.String(length=256), nullable=False))
    op.drop_column('menumaster', 'Menu_Name')
    op.add_column('submenumaster', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenumaster', 'is_active')
    op.add_column('menumaster', sa.Column('Menu_Name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('menumaster', 'menu_name')
    # ### end Alembic commands ###
