"""empty message

Revision ID: 893b0e53133d
Revises: 
Create Date: 2018-02-03 10:10:24.733701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893b0e53133d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('mobile_login', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updation_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_salt', sa.String(length=256), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_login')
    )
    op.create_table('userroles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('useraddress',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('address1', sa.String(length=256), nullable=True),
    sa.Column('address2', sa.String(length=256), nullable=True),
    sa.Column('landmark', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=75), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('mobileno', sa.String(length=15), nullable=True),
    sa.Column('default_flag', sa.Boolean(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('userprofile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updation_date', sa.DateTime(), nullable=True),
    sa.Column('dateofbirth', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('userrolemapping',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['userroles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userrolemapping')
    op.drop_table('userprofile')
    op.drop_table('useraddress')
    op.drop_table('userroles')
    op.drop_table('user')
    op.drop_table('testset')
    # ### end Alembic commands ###
