"""empty message

Revision ID: d7762c6ed2e7
Revises: 9861e0469478
Create Date: 2018-10-17 10:32:01.044800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7762c6ed2e7'
down_revision = '9861e0469478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menumaster',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('Menu_Name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_table('categorymaster',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=512), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('updation_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('submenumaster',
    sa.Column('submenu_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(length=256), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menumaster.menu_id'], ),
    sa.PrimaryKeyConstraint('submenu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submenumaster')
    op.drop_table('categorymaster')
    op.drop_table('menumaster')
    # ### end Alembic commands ###
