"""empty message

Revision ID: e869b6f1d9c1
Revises: 46a14685f059
Create Date: 2018-10-25 21:23:05.337127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e869b6f1d9c1'
down_revision = '46a14685f059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menumaster', sa.Column('menu_name', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menumaster', 'menu_name')
    # ### end Alembic commands ###
